shop/mainapp/urls.py
from django.urls import path

from .views import test_view, ProductDetailView

urlpatterns = [
    path("", test_view, name="base"),
    path("products/<str:ct_model>/<str:slug>/", ProductDetailView.as_view(), name="product_detail")
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainapp.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/mainapp/models.py
import sys
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models
from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.urls import reverse

from io import BytesIO

from PIL import Image

User = get_user_model()

def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={"ct_model": ct_model, "slug": obj.slug})


# ============================================EXCEPTIONS================================================================

class MinResolutionErrorException(Exception):  # Custom exception for validation image resolution
    ...


class MaxResolutionErrorException(Exception):  # Custom exception for validation image resolution
    ...


# ======================================================================================================================

class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:
    objects = LatestProductsManager()

class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        "Bakery": "bakery__count",
        "Bread": "bakery__count",
        "Cake": "cake__count",
        "SemiFinishedProducts": "semifinishedproducts__count"
    }
    
    def get_queryset(self):
        return super().get_queryset()

    def get_categoryes_for_left_sidebar(self):
        models = get_models_for_count("bakery", "bread", "cake", "semifinishedproducts")
        qs = list(self.get_queryset().annotate(*models).values())
        return [dict(name=c["name"], slug=c["slug"], count=c[self.CATEGORY_NAME_COUNT_NAME[c["name"]]]) for c in qs]



class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Categoty name")
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name


class Product(models.Model):
    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (900, 900)
    MAX_IMG_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name="Category", on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name="Product name")
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name="Image")
    description = models.TextField(verbose_name="Description", null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Price")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        new_img = img.convert("RGB")
        resized_new_img = new_img.resize((900, 900), Image.ANTIALIAS)
        filestream = BytesIO()
        resized_new_img.save(filestream, "JPEG", quailty=90)
        filestream.seek(0)
        name = "{}.{}".format(*self.image.name.split("."))
        self.image = InMemoryUploadedFile(
            filestream, "ImageField", name, "jpeg/image", sys.getsizeof(filestream), None
        )

        super().save(*args, **kwargs)


# ================================C A T E G O R Y=======================================================================

class Bakery(Product):
    ingredients = models.TextField(verbose_name="Ingredients", null=True)
    allergens = models.BooleanField(default=True, verbose_name="Allergens")
    allergens_volume = models.CharField(max_length=255, verbose_name='Allergens volume', null=True, blank=True)

    def __str__(self):
        return f"{self.category.name} : {self.title}"

    def get_absolute_url(self):
        return get_product_url(self, "product_detail")

    # @property
    # def allergens(self):
    #     if self.allergens:
    #         return "Yes"
    #     return "No"

class Bread(Product):
    ingredients = models.TextField(verbose_name="Ingredients", null=True)
    allergens = models.BooleanField(default=True, verbose_name="Allergens")
    allergens_volume = models.CharField(max_length=255, verbose_name='Allergens volume', null=True, blank=True)

    def __str__(self):
        return f"{self.category.name} : {self.title}"

    def get_absolute_url(self):
        return get_product_url(self, "product_detail")




class Cake(Product):
    ingredients = models.TextField(verbose_name="Ingredients", null=True)
    allergens = models.BooleanField(default=True, verbose_name="Allergens")
    allergens_volume = models.CharField(max_length=255, verbose_name='Allergens volume', null=True, blank=True)
    weight = models.CharField(max_length=255, verbose_name='Weight (kg)')

    def __str__(self):
        return f"{self.category.name} : {self.title}"

    def get_absolute_url(self):
        return get_product_url(self, "product_detail")


class SemiFinishedProducts(Product):
    ingredients = models.TextField(verbose_name="Ingredients", null=True)
    allergens = models.BooleanField(default=True, verbose_name="Allergens")
    allergens_volume = models.CharField(max_length=255, verbose_name='Allergens volume', null=True, blank=True)
    weight = models.CharField(max_length=255, verbose_name='Weight (kg)')

    def __str__(self):
        return f"{self.category.name} : {self.title}"

    def get_absolute_url(self):
        return get_product_url(self, "product_detail")


# ======================================================================================================================

class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name="Customer", on_delete=models.CASCADE)
    cart = models.ForeignKey("Cart", verbose_name="Cart", on_delete=models.CASCADE, related_name="related_products")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    quantity = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Total price")

    def __str__(self):
        return f"Cart Item: {self.content_object.title} (for cart)"


class Cart(models.Model):
    owner = models.ForeignKey("Customer", verbose_name="Owner", on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name="related_cart")
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Total price")
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name="Phone number")
    address = models.CharField(max_length=255, verbose_name="Adress")
    email = models.EmailField(max_length=255, verbose_name='Email')
    birthday = models.DateField(help_text="Customer birthdate", verbose_name='Birthday')

    def __str__(self):
        return f"User: {self.user.first_name} {self.user.last_name}"

shop/mainapp/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from .models import Bakery, Bread, Cake, SemiFinishedProducts, Category


# Create your views here.

def test_view(request):
    categories = Category.objects.get_categoryes_for_left_sidebar()
    return render(request, 'base.html', {"categories": categories})


class ProductDetailView(DetailView):
    CT_MODEL_MODEL_CLASS = {
        "bakery": Bakery,
        "bread": Bread,
        "cake": Cake,
        "semifinishedproducts": SemiFinishedProducts
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs["ct_model"]]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = "product"
    template_name = "product_detail.html"
    slug_url_kwarg = "slug"

shop/mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    (function($) {
    $("#id_allergens").on("click", function(){
        if ($("#id_allergens").prop("checked") == true){
        $("#id_allergens_volume").prop("readonly", false)
        $("#id_allergens_volume").val("")
        $("#id_allergens_volume").css("background", "white")

        }else{
        $("#id_allergens_volume").prop("readonly", true)
        $("#id_allergens_volume").val("")
        $("#id_allergens_volume").css("background", "lightgray")
        }
    })
    })(django.jQuery);
</script>
{% endblock %}

shop/mainapp/templates/bakery_specification.html
<table class="table">
  <tbody>
    <tr>

      <td>Ingredients: </td>
      <td>{{ product.ingredients}}</td>
    </tr>
      <tr>

      <td>Allergens: </td>
      <td>{{ product.allergens}}</td>
    </tr>
  </tbody>
</table>

shop/mainapp/templates/bread_specification.html
<table class="table">
  <tbody>
    <tr>

      <td>Ingredients: </td>
      <td>{{ product.ingredients}}</td>
    </tr>
      <tr>

      <td>Allergens: </td>
      <td>{{ product.allergens}}</td>
    </tr>
  </tbody>
</table>

shop/mainapp/templates/cake_specification.html
<table class="table">
  <tbody>
    <tr>

      <td>Ingredients: </td>
      <td>{{ product.ingredients}}</td>
    </tr>
      <tr>

      <td>Allergens: </td>
      <td>{{ product.allergens}} </td>
    </tr>
  <tr>

      <td>Weight (kg): </td>
      <td>{{ product.weight}}</td>
    </tr>
  </tbody>
</table>

shop/mainapp/templates/product_detail.html
{% extends "base.html" %}
{% load specifications %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Main Page</a></li>
        <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{ product.title }}</h3>
        <p> Price: {{ product.price }} CHF </p>
        <p> Description: {{ product.description }} </p>

    </div>
    <p class="mt-4"> Specification: </p>

    {{ product|product_spec }}

</div>


{% endblock content %}

shop/mainapp/templates/semifinishedproducts_specification.html
<table class="table">
  <tbody>
    <tr>

      <td>Ingredients: </td>
      <td>{{ product.ingredients}}</td>
    </tr>
      <tr>

      <td>Allergens: </td>
      <td>{{ product.allergens}}</td>
    </tr>
  <tr>

      <td>Weight: </td>
      <td>{{ product.weight }}</td>
      <td>kg</td>
    </tr>
  </tbody>
</table>